export enum BonusPackGetStatus {
  BAD_PACK_NAME = 'BAD_PACK_NAME',
  PACK_ALREADY_GIVEN = 'PACK_ALREADY_GIVEN',
  PACK_NOT_AVAILABLE = 'PACK_NOT_AVAILABLE',
  CHAR_NOT_FOUND = 'CHAR_NOT_FOUND',
  PACK_GIVEN = 'PACK_GIVEN'
}
